### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by pedromvpg** [j4imefoo/nokyc#10]
Anyone else experiencing this connection error?

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/socks.py", line 787, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [Errno 61] Connection refused

```

<img width="1346" alt="Screenshot 2022-06-28 at 19 09 52" src="https://user-images.githubusercontent.com/807505/176253066-70354891-8409-46a7-9663-24b474cbe44c.png">

**Comment by j4imefoo** [comment]
Hi Pedro, I am not getting that but for the looks of it could be that your TOR proxy is on 9150 (tor browser) instead of 9050 (tor daemon)? Could you try or changing the port in the script to 9150 or starting the tor daemon and then running the script?

**Comment by j4imefoo** [comment]
Just to be clear, this script is not starting TOR. TOR has to be started somehow by the user: either by starting the TOR browser (9150) or by starting the TOR daemon (9050)

**Comment by hugoender** [comment]
I'm having the same issue. I am trying to run this script on an RPi. The same RPi also has the Tor daemon running on 9050. I checked that the Tor Daemon is working by setting my desktop Firefox proxy settings to connect to SOCK V5 via the RPi proxy and going to check.torproject.org.

Any help with this would be greatly appreciated.

**Comment by j4imefoo** [comment]
What is the output if you type this in your raspi?
`netstat -putan | grep tor | grep LISTEN`

**Comment by pedromvpg** [comment]
Changed the port to 9150

> Could you try or changing the port in the script to 9150 or starting the tor daemon and then running the script?

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/requests/models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedrogoncalves/Desktop/git/nokyc/nokyc.py", line 75, in <module>
    bisqOffers = Bisq.getOffers(fiat, direction, price_exch, session)
  File "/Users/pedrogoncalves/Desktop/git/nokyc/bisq.py", line 27, in getOffers
    values = f.json()
  File "/opt/homebrew/lib/python3.9/site-packages/requests/models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

<img width="579" alt="image" src="https://user-images.githubusercontent.com/807505/176518538-ee4a6b16-6f87-4614-939d-8871b3865abe.png">

![image](https://user-images.githubusercontent.com/807505/176518512-47f242a2-75af-419c-a3d4-5f49e6ca0512.png)

**Comment by j4imefoo** [comment]
@pedromvpg can you also run this command and let me know the output? It is so we can verify you are actually running Tor and in which port:
`netstat -putan | grep tor | grep LISTEN`
@hugoender Can you paste the output? When you say you are having the same issue, is the output also complaining about the Tor connection?

**Comment by hugoender** [comment]
@j4imefoo Sure. The error message is saying "[Errno 111] Connection refused". Here's the screenshot of the whole message:
![image](https://user-images.githubusercontent.com/6217175/176537447-12f426d4-fdd3-49c7-a155-ae5f5ff487de.png)

**Comment by hugoender** [comment]
@j4imefoo Here are the outputs from the commands you asked to send:
![image](https://user-images.githubusercontent.com/6217175/176538954-0d4272b2-d7ef-4572-9540-c545e1f49f2c.png)

Could it be a torrc config issue? Here's my torrc:
![image](https://user-images.githubusercontent.com/6217175/176539063-a473142d-9a22-40c0-bde9-7919253afb2b.png)

**Comment by j4imefoo** [comment]
Yes, that's it. Please stop tor with `systemctl stop tor`
comment out the two "SocksPort" and "SocksPolicy" lines.
and `systemctl start tor`

**Comment by hugoender** [comment]
> Yes, that's it. Please stop tor with `systemctl stop tor` comment out the two "SocksPort" and "SocksPolicy" lines. and `systemctl start tor`

That did it. It works now. Thank you for your help! Might be a good idea to include a short procedure on how to get Tor up and running on a system such as an RPi. All the guides I read have you specify SocksPort and SocksPolicy as I did

**Comment by j4imefoo** [comment]
@hugoender great that you managed. Actually a procedure to install and configure Tor is outside of the scope of this script or github. Basically all bitcoin software depends on a well-configured Tor! ;)

Great that it works for you!

@pedromvpg If you could verify your Tor installation and run the script we can close this issue

**Comment by pedromvpg** [comment]
In this system (macOS 12.3)
`netstat -putan | grep tor | grep LISTEN`
returns
`netstat: utan: unknown or uninstrumented protocol`

**Comment by j4imefoo** [comment]
Ok, yes, that is cause macOs netstat is bsd netstat and not GNU...
Try this:
`netstat -a -n | grep LISTEN | grep tor`

**Comment by j4imefoo** [comment]
Then you are not running Tor. You need to run Tor manually and have it running to run this script. 
I will close this issue cause it is not related to the script but if you need running Tor feel free to write privatelly to me on Twitter or here
