### ISSUE TITLE
Example in readme is not technically correct

### ISSUE THREAD

**Issue by hugoender** [j4imefoo/nokyc#15]
The example in the Readme shows the following:
`$ nokyc -f eur -t sell -d 8`

This technically does not work unless you set `nokyc` as an alias or other environment variable. The correct example should be as follows:
`$ python3 nokyc.py -f eur -t sell -d 8`

**Comment by j4imefoo** [comment]
python3 not needed if nokyc.py has execution permission. 
Added '.py'
