### ISSUE TITLE
"Exchange Price" does not match those shown on Bisq

### ISSUE THREAD

**Issue by hugoender** [j4imefoo/nokyc#16]
The "Exchange Price" doesn't seem to match the price shown in Bisq:

![12](https://user-images.githubusercontent.com/6217175/176572538-5025a73f-6839-4fda-9645-fbc0ae2cda99.JPG)
![13](https://user-images.githubusercontent.com/6217175/176572543-914c80b5-61cd-42ea-9131-1dcbde6a9574.JPG)

**Comment by j4imefoo** [comment]
These are small enough deviations coming from the fact that:
1. The Wiz price information is not updated every second
2. Bisq is taking that price and keeping for a certain amount of time
3. Our script takes the price at that second and displays it

We can live with this small deviation
