### ISSUE TITLE
Some offers not showing up

### ISSUE THREAD

**Issue by hugoender** [j4imefoo/nokyc#17]
For Robosats for example, there's an offer at a 15% premium that is not showing up in the nokyc output even though I have not specified any deviation:
![14](https://user-images.githubusercontent.com/6217175/176572919-5218b4a2-5e4d-4fb5-8ffe-02a2e95d0d80.PNG)
![15](https://user-images.githubusercontent.com/6217175/176572923-cfbcf2f2-43d0-4a6a-a433-7b621f637ce9.PNG)

**Comment by hugoender** [comment]
I see now that the code has 8% as the default deviation if none is provided. I would recommend setting the default to 999% or something extremely high so it shows all results as this is what a user would expect if they do not explicitly specify the --deviation flag.

**Comment by j4imefoo** [comment]
No, otherwise we are flooding the user terminal with offers. Remember not everybody is using a linux terminal at full screen for this. Cellphone screens are small ;)
